// This file was autogenerated by calcdeps.py
goog.addDependency("test4.js", ['test.test4'], []);
goog.addDependency("deps.js", [], []);
goog.addDependency("test1.js", ['test.test1'], ['test.test2']);
goog.addDependency("test3.js", ['test.test3'], ['test.test4']);
goog.addDependency("test2.js", ['test.test2'], ['test.test3', 'test.test4']);
goog.addDependency("base.js", [], []);
